# -*- coding: utf-8 -*-
"""
Created on Sat Feb 12 13:50:01 2022

@author: Vinay Sawarkar
"""

import random as r

ran_number=r.randrange(1,101)
i=1
info=True
print('''\n\t\t\tIn this game you have to Guess a number generated by computer between 1 to 100
      \t\t\tIf you guess the correct number then you will get the stars from 5 stars
      \t\t\twhich will show you your intelligence as well luck
      
      \t\t\t\t\t\t\tBest Of Luck''')
      
while (True):
    try:
        inpu=int(input("\n"+str(i)+") Guess the number : "))
    except:
        print("\n\t\t\t\t\t*** You entered an invalid number ***")
        info=False
        break;
    i+=1
    if ran_number<inpu:
        print("Your number is Greater than Computer's number")
    elif ran_number>inpu:
        print("Your number is Smaller than Computer's number")
    else :
        print("\n\t\t\t\t\t\tGreat!!!, You guess the correct number")
        
        break;
if info==True:      
    print("\n\t\t\t\t\t\tYou completed this in "+str(i-1)+" steps")
    
    if i<=6:
        print("\t\t\t\t\t\tYou are Exellent \n\t\t\t\t\t\tYOU GOT ***** out of 5 stars")
    elif 6<i<=10:
        print("\t\t\t\t\t\tYou are Good \n\t\t\t\t\t\tYOU GOT **** out of 5 stars")
    else:
        print("\t\t\t\t\t\tYou are Not Good \n\t\t\t\t\t\tYOU GOT ** out of 5 stars")
        
    input()
else:
    input()
